"""empty message

Revision ID: 0e4f9357f096
Revises: 3fef92653e80
Create Date: 2017-01-04 21:20:41.560301

"""

# revision identifiers, used by Alembic.
revision = '0e4f9357f096'
down_revision = '3fef92653e80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
