"""password

Revision ID: 3fef92653e80
Revises: None
Create Date: 2016-12-24 09:57:02.055603

"""

# revision identifiers, used by Alembic.
revision = '3fef92653e80'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_password', sa.String(length=28), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hash_password')
    ### end Alembic commands ###
