"""empty message

Revision ID: 4da5ea5490c2
Revises: 3bb4b464b166
Create Date: 2017-01-14 13:21:29.307948

"""

# revision identifiers, used by Alembic.
revision = '4da5ea5490c2'
down_revision = '3bb4b464b166'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('html_body', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'html_body')
    ### end Alembic commands ###
