"""empty message

Revision ID: ac2d15639f30
Revises: 0e4f9357f096
Create Date: 2017-01-05 21:20:51.490982

"""

# revision identifiers, used by Alembic.
revision = 'ac2d15639f30'
down_revision = '0e4f9357f096'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permission', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'permission')
    ### end Alembic commands ###
